version: '3'
services:
    web:
        image: webdevops/php-apache-dev:7.3-alpine
        container_name: estadao_web
        restart: always
        user: application
        environment:
          - WEB_ALIAS_DOMAIN=local
          - WEB_DOCUMENT_ROOT=/app/public
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
          - ./estadao:/app:cached
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
        networks:
          - network1
        links:
          - mysql
    mysql:
        image: mysql:5.7
        stdin_open: true
        tty: true
        container_name: estadao_mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=estadao
        networks:
          - network1
        volumes:
          - db-data:/var/lib/mysql
    phpmyadmin:
        container_name: estadao_phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - PMA_HOST=mysql
          - MYSQL_ROOT_PASSWORD=root
          - PMA_USER=root
          - PMA_PASSWORD=root
        ports:
          - "8080:80"
        links:
          - mysql:db-data
        depends_on:
          - mysql
        networks:
          - network1
volumes:
    db-data:
        external: false
    data01:
        driver: local
networks:
  network1:
    driver: bridge
